In [1]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

-9.51619735392994e-16

#### 역행렬과 선형 연립방정식의 해 (2.4.26)
$$x = A^-1 b$$

In [2]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [3]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [4]:
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [5]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [8]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [11]:
# x, resid, rank, s 모두 알려주긴 하지만 이방법이 위 방법보다 x를 구하기 좋음
# A,x,b  는 각각 계수행렬 미지수벡터 상수벡터
# Ax=b 같은 꼴일때 x값을 구해주는
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\shs40\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


array([[1.],
       [1.],
       [1.]])

In [13]:
# 연습 문제 2.4.5
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE' 변수와 4개행만 사용
b = y[:4]

In [14]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [15]:
b

array([24. , 21.6, 34.7, 33.4])

In [18]:
# lstsq를 사용한 방법
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\shs40\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [22]:
# inv를 구해서 x=A^-1b꼴로 구해줌
Ainv= np.linalg.inv(A)
x=np.dot(Ainv,b)
print(x)

[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


### 2.4.47

In [23]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [24]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [25]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [26]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [27]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [28]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\shs40\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [29]:
resid, np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.0016666666666666698)

### 2.4.6

In [5]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [6]:
x, resid, rank, s = np.linalg.lstsq(X, y)
print(x)

[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]


C:\Users\shs40\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.
