$\alpha$와 $\beta$ 값이 같다.

$$ \alpha = \beta $$

$\alpha$
$\beta$
$\gamma$
$\delta$
$\epsilon$
$\zeta$
$\eta$
$\theta$
$\kappa$
$\lambda$
$\mu$
$\nu$
$\xi$
$\pi$
$\rho$
$\sigma$
$\tau$
$\phi$
$\chi$
$\psi$
$\omega$

$$ \alpha 
\beta 
\gamma 
\delta 
\epsilon 
\zeta 
\eta 
\theta 
\kappa 
\lambda 
\mu 
\nu 
\xi 
\pi 
\rho 
\sigma 
\tau 
\phi 
\chi 
\psi 
\omega $$

In [43]:
# 

In [13]:
x2=np.array([[4.9],[3.0],[1.4],[0.2]])

In [14]:
x2

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

In [16]:
x2=np.array([[5.1,3.5,1.4,0.2],[4.9,3.0,1.4,0.2]])

In [17]:
x2

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [19]:
x2.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [20]:
x2.T.T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

### 연습 문제 2.1.4

In [26]:
np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [27]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [29]:
np.array([[1,2],
          [3,4]])

array([[1, 2],
       [3, 4]])

In [32]:
np.diag([1,2,1])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [31]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
sym=np.array([[1,2,3],
              [2,2,2],
              [3,2,2]])

In [41]:
sym.T

array([[1, 2, 3],
       [2, 2, 2],
       [3, 2, 2]])

In [42]:
# 

In [39]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

x.T @ y

array([[32]])

In [40]:
(x.T @ y)[0][0]

32

### 연습문제 2.2.1

In [48]:
p=np.array([[1000000],[800000],[500000]])
n=np.array([[3],[4],[5]])

In [50]:
p.T@n

array([[8700000]])

### 연습문제 2.2.3

In [52]:
from sklearn.datasets import load_digits
x = load_digits().data

In [53]:
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [55]:
x[0,:]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [56]:
x[9,:]

array([ 0.,  0., 11., 12.,  0.,  0.,  0.,  0.,  0.,  2., 16., 16., 16.,
       13.,  0.,  0.,  0.,  3., 16., 12., 10., 14.,  0.,  0.,  0.,  1.,
       16.,  1., 12., 15.,  0.,  0.,  0.,  0., 13., 16.,  9., 15.,  2.,
        0.,  0.,  0.,  0.,  3.,  0.,  9., 11.,  0.,  0.,  0.,  0.,  0.,
        9., 15.,  4.,  0.,  0.,  0.,  9., 12., 13.,  3.,  0.,  0.])

In [59]:
# 1번 과9번의 내적 ->유사도
# 값이 클수록 유사 -> 0과 만나는 일이 적기때문에 유사할수록 값이 커짐
x[0,:]@x[9,:]

2807.0

### 연습문제 2.2.4

In [60]:
a=np.array([[1,2,3],
           [4,5,6]])
b=np.array([[1,2],
           [3,4],
           [5,6]])

In [62]:
a@b

array([[22, 28],
       [49, 64]])

In [63]:
b@a

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [64]:
a=np.array([1,2,3])
b=np.array([[4,7],
           [5,8],
            [6,9]])

In [65]:
a@b

array([32, 50])

In [66]:
# b@a 는 계산되지 않는게 정상
b@a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [67]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[5,6],
           [7,8]])

In [68]:
a@b

array([[19, 22],
       [43, 50]])

In [69]:
b@a

array([[23, 34],
       [31, 46]])

In [70]:
a=np.array([[1,2],
           [3,4],
           [5,6]])

In [71]:
a.T@a

array([[35, 44],
       [44, 56]])

In [72]:
a@a.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [79]:
a=np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [80]:
a@a.T

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [82]:
a.T@a

array([[14]])

### 연습 문제 2.2.5

In [83]:
from sklearn.datasets import load_iris
X = load_iris().data

In [85]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [86]:
len(X)

150

In [90]:
one=np.ones(4)

In [94]:
sum_iris=X@one

In [101]:
sum_iris=sum_iris.reshape(150,1)

In [104]:
X_bar=1/4 * sum_iris

In [105]:
X_bar

array([[2.55 ],
       [2.375],
       [2.35 ],
       [2.35 ],
       [2.55 ],
       [2.85 ],
       [2.425],
       [2.525],
       [2.225],
       [2.4  ],
       [2.7  ],
       [2.5  ],
       [2.325],
       [2.125],
       [2.8  ],
       [3.   ],
       [2.75 ],
       [2.575],
       [2.875],
       [2.675],
       [2.675],
       [2.675],
       [2.35 ],
       [2.65 ],
       [2.575],
       [2.45 ],
       [2.6  ],
       [2.6  ],
       [2.55 ],
       [2.425],
       [2.425],
       [2.675],
       [2.725],
       [2.825],
       [2.425],
       [2.4  ],
       [2.625],
       [2.5  ],
       [2.225],
       [2.55 ],
       [2.525],
       [2.1  ],
       [2.275],
       [2.675],
       [2.8  ],
       [2.375],
       [2.675],
       [2.35 ],
       [2.675],
       [2.475],
       [4.075],
       [3.9  ],
       [4.1  ],
       [3.275],
       [3.85 ],
       [3.575],
       [3.975],
       [2.9  ],
       [3.85 ],
       [3.3  ],
       [2.875],
       [3.65 ],
       [